---

- name: Register nagios-nrpe-server latest available version
  shell:
    apt-cache madison nagios-nrpe-server |
      awk -F'| *' 'NR == 1 { print $3 }'
  register:
    nagios_nrpe_server_version
  changed_when: False
  tags:
    - nrpe_agent_install

- name: Set fact is_nrpe_v3_available
  set_fact:
    is_nrpe_v3_available={{ nagios_nrpe_server_version.stdout | regex_replace('^(\d+\.\d+).*', '\\1') | version_compare('3.0', '>=', strict=True) }}
  tags:
    - apt
    - nrpe_agent_install

# NOTE Add the debian testing repo from where we will pull in nrpe >= 3.0
- name: Add debian testing repo
  template:
    src:   etc/apt/sources.list.d/nrpe-debian-testing.list.j2
    dest: /etc/apt/sources.list.d/nrpe-debian-testing.list
  when: 
    - is_nrpe_v3_available != True
  register:
    nrpe_debian_testing_repo_installed
  tags:
    - apt
    - repo
    - nrpe_agent_install

- name: Update apt cache
  apt: 
    update_cache: yes
  when: 
    - nrpe_debian_testing_repo_installed.changed
  tags:
    - apt
    - nrpe_agent_install

- name: Install nagios-nrpe-{server,plugins} from debian testing
  apt: 
    pkg:   '{{ item.package }}'
    state: present
    default_release: testing
  with_items: "{{ nrpe_agent_Debian }}"
  when:
    - nrpe_debian_testing_repo_installed.changed
  tags:
   - nrpe_agent_install

- name: Install nagios-nrpe-{server,plugins} from debian stable
  apt: 
    pkg:   '{{ item.package }}'
    state: latest
  with_items: "{{ nrpe_agent_Debian }}"
  when:
    - nrpe_debian_testing_repo_installed.changed == False
  tags:
   - nrpe_agent_install

- name: Copy nrpe configuration
  template:
    src:     nrpe.cfg.j2
    dest:    '{{ nrpe_agent_config }}'
    owner:   root
    group:   root
    mode:    0644
    backup:  yes
  notify:
   - restart nagios-nrpe-server
  tags:
   - nrpe_agent_install
   - nrpe_agent_config

- name: Remove debian testing repo
  file:
    path:  /etc/apt/sources.list.d/nrpe-debian-testing.list
    state: absent
  when: 
    - nrpe_debian_testing_repo_installed.changed
  tags:
    - apt
    - repo
    - nrpe_agent_install

- name: Update apt cache
  apt: 
    update_cache: yes
    cache_valid_time: 3600
  when: 
    - nrpe_debian_testing_repo_installed.changed
  tags:
    - apt
    - nrpe_agent_install

